# ============================================================ #
#           Configuration for VypnitoCombat Plugin             #
# ============================================================ #

# --- Global PvP Settings ---
# Master switch for server-wide PvP.
# If set to false, no players can damage each other directly.
global_pvp_enabled: true

# --- Protections for when Global PvP is Disabled ---
pvp_protections:
  # If true, prevents players from placing lava near other players when global PvP is off.
  prevent_lava_placement_near_players: true
  # The radius (in blocks) to check for nearby players when placing lava.
  lava_check_radius: 3
  # If true, prevents players from harming others with splash potions when global PvP is off.
  prevent_harmful_splash_potions: true
  # List of potion effects considered harmful and will be blocked.
  # Effect names from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
  harmful_potion_effects:
    - HARM
    - POISON
    - SLOWNESS
    - WEAKNESS
    - WITHER

# --- Core Combat Settings ---
# Time in seconds that a player remains in combat after the last hit.
combat_duration_seconds: 10
# Show a countdown timer in the action bar while a player is in combat.
action_bar_timer: true
# If true, combat tags for both the victim and the attacker will be removed upon a player's death.
end_combat_on_death: true

# --- Custom Death Message ---
death_messages:
  # If true, a custom message will be used when a player dies while in combat.
  use_custom_when_in_combat: false

# --- Health Indicators ---
health_indicators:
  # Shows a BossBar with the enemy's health at the top of the attacker's screen.
  bossbar:
    enabled: true

  # Shows text with the enemy's health directly above their head.
  overhead:
    enabled: true

# --- Region Protections (Requires WorldGuard) ---
region_protections:
  # Defines the method used to prevent players from entering safe zones while in combat.
  # Available options:
  #   VISUAL_BORDER - (PERFORMANCE INTENSIVE) Shows a dynamic wall of fake blocks.
  #   PUSHBACK      - Physically bounces the player back. Simpler and less resource-intensive. -RECOMMENDED
  #   NONE          - Disables this protection entirely.
  entry_prevention_method: PUSHBACK

  # --- Settings for the PUSHBACK method ---
  # How strong the "bounce" effect is when a player is pushed back.
  pushback_strength: 0.8

  # --- Settings for the VISUAL_BORDER method ---
  # How often (in server ticks, 20 ticks = 1 second) the plugin checks a player's position.
  visualization_check_interval_ticks: 10
  # The radius (in blocks) around the player in which region borders will be displayed.
  # WARNING: High values can cause lag! Recommended: 10-15.
  visualization_display_radius: 15
  # The material of the visual wall.
  visualization_wall_material: "RED_STAINED_GLASS"

# --- In-Combat Restrictions ---
combat_restrictions:
  block_riptide: true
  # This option is disabled by default because it can interfere with Mending.
  damage_elytra_on_restrict: false
  blocked_items_in_combat:
    - ELYTRA
  blocked_commands_in_combat:
    - "home"
    - "spawn"
    - "tpa"
    - "warp"

# --- Cooldowns After Combat ---
cooldowns_after_combat:
  elytra_seconds: 20
  ender_pearl_seconds: 15

# --- Punishments for Combat Logging ---
punishments:
  kill_player: true
  execute_commands:
    - "broadcast &c%player% combat logged and was punished!"

# --- Integrations ---
integrations:
  worldguard:
    enabled: true

# --- Update Checker ---
update_checker:
  enabled: true
  # Do not change.
  spigot_resource_id: 125821